apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: svcpermissions.lstack.k8s.io
spec:
  group: lstack.k8s.io
  version: v1
  names:
    kind: SvcPermission
    plural: svcpermissions
    shortNames:
      - svcp
  scope: Cluster
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: svcp-sa
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: svcp-sa-crb
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: svcp-sa
    namespace: kube-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: svcp-webhook
  namespace: kube-system
  labels:
    app: svcp-webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: svcp-webhook
  template:
    metadata:
      labels:
        app: svcp-webhook
    spec:
      containers:
        - name: svcp-webhook
          image: registry.cn-hangzhou.aliyuncs.com/launcher-agent-only-test/svcp:v1
          imagePullPolicy: Always
          volumeMounts:
            - name: webhook-certs
              mountPath: /etc/webhook/certs
              readOnly: true
      serviceAccountName: svcp-sa
      volumes:
        - name: webhook-certs
          secret:
            secretName: svcp-webhook-secret

