apiVersion: v1
kind: Service
metadata:
  name: svcp-webhook
  namespace: kube-system
  labels:
    app: svcp-webhook
spec:
  ports:
  - port: 443
    targetPort: 8443
  selector:
    app: svcp-webhook
